### ISSUE TITLE
Potential of leaking secrets

### ISSUE THREAD

**Issue by nickpadovani** [Adawg4/openapi-autospec#1]
To preface - this tool is awesome, however a suggestion for improvement -- it seems the app properly recognizes authorization / security schemes based on:
<img width="315" alt="Screenshot 2024-03-25 at 9 33 10 PM" src="https://github.com/Adawg4/openapi-autospec/assets/23531283/de65cd0b-1241-4949-a42e-b383f7eda757">

However, I think given it recognizes this, it should obfuscate, omit, or remove the actual secret it intercepts (in this case a bearer token):
<img width="477" alt="Screenshot 2024-03-25 at 9 34 16 PM" src="https://github.com/Adawg4/openapi-autospec/assets/23531283/1619bcba-6c9f-4d58-942a-92a232d7d057">

Assuming someone had GHAS or other security scanning turned on, it would get caught, but if someone blindly committed the output documentation and didn't have this kind of scanning, they could have a bad time (especially in a public repo).

**Comment by japentaca** [comment]
I think the objetive of this tool is for development environments, where secrets are known from the same people who will get the results from the tool.
Anyway, some kind of redaction dictionary functionality would be good.
